server:
  port: 8088
  contextPath: /housing
#  ssl:
#    key-store: file:///c:/certificates/mykeystore.jks
#    key-store-password: password123


spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://mock-housing-db\\crm:1433;database=mock-housing;sendStringParametersAsUnicode=false
    username: cxm
    password: Srgsys01


address-lookup:
  api-key: EF4vRVWAg02De56eHnchsw12550


logging:
  level: com.daledev=DEBUG
  file: c:/logs/mock-housing-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"